### ISSUE TITLE
Implement Ruff for Code Quality

### ISSUE THREAD

**Issue by sunr4y** [Daily-Projects-Server/virtual-marketplace#72]
We need to implement Ruff, a fast Python linter, to ensure code quality and adherence to best practices. Ruff can help us catch common errors, enforce coding standards, and maintain a clean codebase. Below are the key areas that need improvement and the steps to implement Ruff.

## Benefits of Using Ruff

1. **Speed:** Ruff is designed to be fast, making it suitable for large codebases.
2. **Comprehensive:** It supports a wide range of linting rules and can catch many common errors.
3. **Configurable:** Ruff allows for extensive configuration, enabling us to tailor it to our specific needs.
4. **Integration:** It can be easily integrated into our development workflow, including pre-commit hooks.

## Steps to Implement Ruff

1. **Install Ruff:**
   - Add Ruff to the project's dependencies.
   - Install Ruff using pip:
     ```bash
     pip install ruff
     ```

2. **Configure Ruff:**
   - Create a `pyproject.toml` file in the root of the project if it doesn't already exist.
   - Add the following configuration to the `pyproject.toml` file:
     ```toml
     [tool.ruff]
     # Enable all rules by default
     select = ["E", "F", "W", "C", "N", "Q", "B", "A"]
     # Exclude specific rules
     ignore = ["E501"]
     # Apply Ruff only to the backend folder
     src = ["backend"]
     ```

3. **Implement Pre-commit Hooks:**
   - Add pre-commit to the project's dependencies.
   - Install pre-commit using pip:
     ```bash
     pip install pre-commit
     ```
   - Add pre-commit to `requirements.txt`:
     ```
     pre-commit
     ```
   - Create a `.pre-commit-config.yaml` file in the root of the project if it doesn't already exist.
   - Add the following configuration to the `.pre-commit-config.yaml` file:
     ```yaml
     repos:
       - repo: https://github.com/astral-sh/ruff
         rev: v0.0.1  # Use the latest version
         hooks:
           - id: ruff
             args: ["--fix"]
     ```

4. **Set Up Pre-commit:**
   - Run the following command to install the pre-commit hook:
     ```bash
     pre-commit install
     ```

5. **Run Ruff:**
   - Run Ruff manually to check for any existing issues in the codebase:
     ```bash
     ruff check backend
     ```

6. **Skip Certain Checks:**
   - If certain checks need to be skipped for specific files or directories, add them to the `exclude` section in the `pyproject.toml` file:
     ```toml
     [tool.ruff]
     exclude = ["backend/migrations/*", "backend/tests/*"]
     ```

## Reference Documentation

- [Ruff Documentation](https://github.com/charliermarsh/ruff)
- [Pre-commit Documentation](https://pre-commit.com/)

By implementing Ruff, we can ensure that the codebase remains clean, maintainable, and adheres to best practices. This will help catch errors early and improve the overall quality of the project.
